// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: room-service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на создание комнаты
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	TrackUrl      string                 `protobuf:"bytes,2,opt,name=track_url,json=trackUrl,proto3" json:"track_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_room_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *CreateRoomRequest) GetTrackUrl() string {
	if x != nil {
		return x.TrackUrl
	}
	return ""
}

type RoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	TrackUrl      string                 `protobuf:"bytes,3,opt,name=track_url,json=trackUrl,proto3" json:"track_url,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // play/pause
	Users         []string               `protobuf:"bytes,6,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomResponse) Reset() {
	*x = RoomResponse{}
	mi := &file_room_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResponse) ProtoMessage() {}

func (x *RoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResponse.ProtoReflect.Descriptor instead.
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{1}
}

func (x *RoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RoomResponse) GetTrackUrl() string {
	if x != nil {
		return x.TrackUrl
	}
	return ""
}

func (x *RoomResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RoomResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RoomResponse) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

// Присоединение к комнате
type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_room_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Управление воспроизведением
type SetPlaybackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`        // play/pause/seek
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // таймкод
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPlaybackRequest) Reset() {
	*x = SetPlaybackRequest{}
	mi := &file_room_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPlaybackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlaybackRequest) ProtoMessage() {}

func (x *SetPlaybackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlaybackRequest.ProtoReflect.Descriptor instead.
func (*SetPlaybackRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{3}
}

func (x *SetPlaybackRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SetPlaybackRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SetPlaybackRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Получение состояния комнаты
type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_room_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_room_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetStateRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

var File_room_service_proto protoreflect.FileDescriptor

const file_room_service_proto_rawDesc = "" +
	"\n" +
	"\x12room-service.proto\x12\x04room\"I\n" +
	"\x11CreateRoomRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1b\n" +
	"\ttrack_url\x18\x02 \x01(\tR\btrackUrl\"\xa9\x01\n" +
	"\fRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1b\n" +
	"\ttrack_url\x18\x03 \x01(\tR\btrackUrl\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05users\x18\x06 \x03(\tR\x05users\"C\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"c\n" +
	"\x12SetPlaybackRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"*\n" +
	"\x0fGetStateRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId2\xf3\x01\n" +
	"\vRoomService\x129\n" +
	"\n" +
	"CreateRoom\x12\x17.room.CreateRoomRequest\x1a\x12.room.RoomResponse\x125\n" +
	"\bJoinRoom\x12\x15.room.JoinRoomRequest\x1a\x12.room.RoomResponse\x12;\n" +
	"\vSetPlayback\x12\x18.room.SetPlaybackRequest\x1a\x12.room.RoomResponse\x125\n" +
	"\bGetState\x12\x15.room.GetStateRequest\x1a\x12.room.RoomResponseB\x12Z\x10main/pkg/api;apib\x06proto3"

var (
	file_room_service_proto_rawDescOnce sync.Once
	file_room_service_proto_rawDescData []byte
)

func file_room_service_proto_rawDescGZIP() []byte {
	file_room_service_proto_rawDescOnce.Do(func() {
		file_room_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_service_proto_rawDesc), len(file_room_service_proto_rawDesc)))
	})
	return file_room_service_proto_rawDescData
}

var file_room_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_room_service_proto_goTypes = []any{
	(*CreateRoomRequest)(nil),  // 0: room.CreateRoomRequest
	(*RoomResponse)(nil),       // 1: room.RoomResponse
	(*JoinRoomRequest)(nil),    // 2: room.JoinRoomRequest
	(*SetPlaybackRequest)(nil), // 3: room.SetPlaybackRequest
	(*GetStateRequest)(nil),    // 4: room.GetStateRequest
}
var file_room_service_proto_depIdxs = []int32{
	0, // 0: room.RoomService.CreateRoom:input_type -> room.CreateRoomRequest
	2, // 1: room.RoomService.JoinRoom:input_type -> room.JoinRoomRequest
	3, // 2: room.RoomService.SetPlayback:input_type -> room.SetPlaybackRequest
	4, // 3: room.RoomService.GetState:input_type -> room.GetStateRequest
	1, // 4: room.RoomService.CreateRoom:output_type -> room.RoomResponse
	1, // 5: room.RoomService.JoinRoom:output_type -> room.RoomResponse
	1, // 6: room.RoomService.SetPlayback:output_type -> room.RoomResponse
	1, // 7: room.RoomService.GetState:output_type -> room.RoomResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_room_service_proto_init() }
func file_room_service_proto_init() {
	if File_room_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_service_proto_rawDesc), len(file_room_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_service_proto_goTypes,
		DependencyIndexes: file_room_service_proto_depIdxs,
		MessageInfos:      file_room_service_proto_msgTypes,
	}.Build()
	File_room_service_proto = out.File
	file_room_service_proto_goTypes = nil
	file_room_service_proto_depIdxs = nil
}
